name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SHOULD_DEPLOY_AND_TAG: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      # Backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.4'

      - name: Install Backend dependencies
        working-directory: backend
        run: |
          npm ci

      - name: Lint Backend code
        working-directory: backend
        run: |
          npm run lint

      - name: Run unit tests for Backend
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
        working-directory: backend
        run: |
          npm run test

      # Frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.4'

      - name: Install Frontend dependencies
        working-directory: frontend
        run: |
          npm ci

      - name: Run unit tests for Frontend
        working-directory: frontend
        run: |
          npm run test

      # End to end tests
      - name: Run end to end tests
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          PORT: 3001
        run: |
          cd ./backend && npm run start:test &
          cd ./frontend && npm run dev &
          cd ./end-to-end-tests && npm ci && npx playwright install --with-deps && npm run test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./end-to-end-tests/playwright-report/
          retention-days: 30

      # Combined Build and Deployment Step
      - name: Set up Flyctl
        if: ${{ env.SHOULD_DEPLOY_AND_TAG == 'true' }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build and Deploy
        if: ${{ env.SHOULD_DEPLOY_AND_TAG == 'true' }}
        run: |
          cd frontend
          npm run build
          cd ..

          rm -rf ./backend/dist
          cp -r ./frontend/dist ./backend

          cd backend
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    needs: [deployment_pipeline]
    if: ${{ github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        if: ${{ env.SHOULD_DEPLOY_AND_TAG == 'true' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: false
